[package]
name = "fm-plugin"
version = "0.1.0"
authors = ["mutantcows <mutantcows@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
widestring = "*"
directories = "*"
pdf_forms = "*"
serde_json = "*"
phf = { version = "*", features = ["macros"] }

[build-dependencies]
bindgen = "*"
cc = "*"
libc = "*"

[package.metadata.cargo-post.dependencies]
directories = "*"
toml = "*"
serde = { version = "1.0", features = ["derive"] }
