[package]
name = "fm_plugin"
version = "0.1.0"
authors = ["mutantcows <mutantcows@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
widestring = "*"
directories = "*"

[build-dependencies]
bindgen = "*"
cc = "*"
libc = "*"
toml = "*"
serde = { version = "1.0", features = ["derive"] }

[package.metadata.cargo-post.dependencies]
directories = "*"
toml = "*"
serde = { version = "1.0", features = ["derive"] }
