[filemaker]
ext_path = "/path/to/Extentions"
bin_path = "/Applications/FileMaker Pro.app"
kill = true
launch = true

[plugin]
name = "plugin name"
bundle = true
move_to_ext = true
sign_code = false
cert_path = ""

[log]
path = "/path/to/plugin.log"
clear_on_launch = true
