name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cargo Post
      run: cargo install cargo-post
    - name: Download FileMaker
      run: --output "FileMaker Pro 19.msi" --key "${{ secrets.FLASK_PRIVATE_KEY }}" "sftp://root@167.99.7.34:22/root/FileMaker Pro 19.msi"
    - name: Install FileMaker
      run: msiexec /i "FileMaker Pro 19.msi" /qn
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
