name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cargo Post
      run: cargo install cargo-post
    - name: Download FileMaker
      run: curl https://downloads.claris.com/esd/fmp_19.2.1.14_x64.exe --output fmp_19.2.1.14_x64.exe
    - name: Install FileMaker
      run: fmp_19.2.1.14_x64.exe
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
